# @package _global_

defaults:
  - _self_
  - data: images
  - model: detector
  - callbacks: null
  - logger: null
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "eval"

tags: ["dev"]
seed: 12345
is_local: False
multiclass: True

data:
  data_root_dir: ???
  batch_size: 256
  multiclass: "${multiclass}"
  methods: ["original", "dalle-3-images", "diffusiondb", "midjourney-images", "midjourney_tti", "realisticSDXL"]

  patch_size: 224
  top_k_patches: 5
  patch_selection_criterion: "contrast"
  patch_strategy: "max"

result_save_path: ???
ckpt_path: ???